export const UserActionsTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    SIGN_IN_START:'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE'
}